name: build_go_binary
on:
  workflow_dispatch:
  pull_request:
    branches:
      - development

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: solid-web
        run: bun install --frozen-lockfile

      - name: Build web app
        working-directory: solid-web
        run: bun run build

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: 'true'

      - name: Build go Binary
        run: go build -ldflags="-s -w" -o finance-project-management .