name: go_test

on:
  workflow_dispatch:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.4.0"

      - name: Install web dependencies
        working-directory: solid-web
        run: bun install --frozen-lockfile

      - name: Build web application
        working-directory: solid-web
        run: bun run build

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: 'true'

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build ldflags="-s -w" -o main .

      - name: Run tests
        run: go test -race -vet=off ./...